# Generated by Django 4.0.2 on 2022-02-11 13:53

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_id', models.BigIntegerField(blank=True, null=True)),
                ('achievement_count', models.IntegerField(blank=True, null=True)),
                ('average_cadence', models.FloatField(blank=True, null=True)),
                ('average_heartrate', models.FloatField(blank=True, null=True)),
                ('average_speed', models.FloatField(blank=True, null=True)),
                ('comment_count', models.IntegerField(blank=True, null=True)),
                ('distance', models.FloatField(blank=True, null=True)),
                ('elapsed_time', models.FloatField(blank=True, null=True)),
                ('elevation_high', models.IntegerField(blank=True, null=True)),
                ('elevation_low', models.IntegerField(blank=True, null=True)),
                ('end_latlng', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(blank=True, null=True), blank=True, default=list, null=True, size=None)),
                ('kudo_count', models.IntegerField(blank=True, null=True)),
                ('location_city', models.TextField(blank=True, null=True)),
                ('location_state', models.TextField(blank=True, null=True)),
                ('location_country', models.TextField(blank=True, null=True)),
                ('map_latitude', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(blank=True, null=True), blank=True, default=list, null=True, size=None)),
                ('map_longitude', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(blank=True, null=True), blank=True, default=list, null=True, size=None)),
                ('map_centroid', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(blank=True, null=True), blank=True, default=list, null=True, size=None)),
                ('map_elevation', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(blank=True, null=True), blank=True, default=list, null=True, size=None)),
                ('max_heartrate', models.FloatField(blank=True, null=True)),
                ('max_speed', models.FloatField(blank=True, null=True)),
                ('moving_time', models.FloatField(blank=True, null=True)),
                ('name', models.TextField(blank=True, null=True)),
                ('photo_count', models.IntegerField(blank=True, null=True)),
                ('pr_count', models.IntegerField(blank=True, null=True)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('start_date_local', models.DateTimeField(blank=True, null=True)),
                ('start_latitude', models.FloatField(blank=True, null=True)),
                ('start_longitude', models.FloatField(blank=True, null=True)),
                ('start_latlng', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(blank=True, null=True), blank=True, default=list, null=True, size=None)),
                ('suffer_score', models.IntegerField(blank=True, null=True)),
                ('timezone', models.TextField(blank=True, max_length=2000, null=True)),
                ('total_elevation_gain', models.IntegerField(blank=True, null=True)),
                ('type', models.TextField(blank=True, max_length=2000, null=True)),
                ('utc_offset', models.BigIntegerField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
